Move updateCheckInterval to config #23
DAVFoundation/dav-cli pull request #26
Opened 2018-02-28 16:33 UTC by codisteinborn

## Description
Moved 'notifier' as 'update_check_interval' to the config file to match the implementation of defaultpassword.

## Related Issue

#23 

## Motivation and Context

This helps standardize the code style of this project.

## How Has This Been Tested?

Tested by running dav-cli in console

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-03-01 16:50 UTC, cg-cnu requested changes
Hey @codisteinborn Thanks for your interest in fixing this issue. 
You have completely removed the `updateNotifier` and `pkg`. The idea of this issue is to move the magic number `86400000` into the config file. Let me know if things are not clear, I will try to help 🙂

2018-03-01 16:50 UTC, cg-cnu commented on src/lib/updateNotifier.js
> +const notifier = config('update_check_interval');
Hey @codisteinborn You have completely replaced the notifier object.
You are supposed to change only `updateCheckInter : config('update_check_interval');` Please fix it and update your pr

2018-03-02 04:04 UTC, codisteinborn commented
I see what you mean. Updating now!

2018-03-28 01:02 UTC, cg-cnu commented
Hey @codisteinborn there is a merge conflict. Can you resolve it and update the pr so that we can merge it. Thanks! 🙂

2018-04-02 17:17 UTC, cg-cnu commented
Hey @codisteinborn Are you still interested in fixing this PR or please let us know, else will assign it to some one else! Thanks! 🙂

2018-04-02 18:10 UTC, codisteinborn commented
Just resolved the merge conflict!

2018-04-10 09:24 UTC, merged